# Generated by Django 3.1.5 on 2021-04-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_booksearchmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksearchmodel',
            options={},
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='Data_books',
            field=models.BooleanField(default=False, verbose_name='Libros de Bases de Datos'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='others_books',
            field=models.BooleanField(default=False, verbose_name='Otros'),
        ),
    ]
